---
title: "shinyActivationFunction"
author: "Dharmesh Bhuva"
date: "29 August 2017"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE, include=FALSE}
source('../GraphGRN-methods.R')
source('../GraphGRN.R')
source('../SimulationGRN-methods.R')
source('../SimulationGRN.R')
source('analysis_methods.R')
library(igraph)
library(ggplot2)
library(plotly)
library(grid)
library(ggraph)
library(deSolve)
library(foreach)
library(nleqslv)
library(mclust)
library(shiny)
library(stringr)

#activation function
fAct <- function(TF, EC50 = 0.5, n = 1.39) {
  B = (EC50 ^ n - 1) / (2 * EC50 ^ n - 1)
  K_n = (B - 1)
  act = B * TF ^ n / (K_n + TF ^ n)
  
  return(act)
}

#multiplot function
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
	
	# Make a list from the ... arguments and plotlist
	plots <- c(list(...), plotlist)
	
	numPlots = length(plots)
	
	# If layout is NULL, then use 'cols' to determine layout
	if (is.null(layout)) {
		# Make the panel
		# ncol: Number of columns of plots
		# nrow: Number of rows needed, calculated from # of cols
		layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
						 ncol = cols, nrow = ceiling(numPlots/cols))
	}
	
	if (numPlots==1) {
		print(plots[[1]])
		
	} else {
		# Set up the page
		grid.newpage()
		pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
		
		# Make each plot, in the correct location
		for (i in 1:numPlots) {
			# Get the i,j matrix positions of the regions that contain this subplot
			matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
			
			print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
											layout.pos.col = matchidx$col))
		}
	}
}

nsize = 40
```

#Conditional dependence
```{r, echo=FALSE}
plotds <- function(d, ptitle, rteqn, histoplot){
  plotd = as.data.frame(t(d))
  cors = cor(plotd)
  cors = round(cors, digits = 2)
  #score calculation
  classf = Mclust(d['B',], verbose = F)$classification
  #calc cors
  corlowB = round(cor(plotd[classf == 1, 1:2])[1, 2], digits = 2)
  corhighB = round(cor(plotd[classf == 2, 1:2])[1, 2], digits = 2)
  classf[classf == 1] = paste('low B (', corlowB, ')', sep = '')
  classf[classf == 2] = paste('high B (', corhighB, ')', sep = '')
  plotd$BClass = classf
  
  p1 = ggplot(plotd, aes(A, C, colour = B)) + geom_point() +
    scale_colour_distiller(palette = 'RdPu', direction = 1) +
    ggtitle(paste(ptitle, ' (cor = ', cors['A', 'C'], ')', sep = '')) +
    facet_wrap(~BClass) +
    theme_minimal() +
    theme(
      panel.grid.minor = element_blank(),
      axis.line = element_line(colour="black"),
      strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0")
    )
  
  #activation function plots
  f = function(A, B, rateeqn) {
    D = 0
    C = 0
    eval(parse(text = rateeqn))
  }
  
  #plot activation functions
  plotd = as.data.frame(t(d))
  pdata = expand.grid('A' = seq(0, 1, length.out = 100), 'B' = seq(0, 1, length.out = 100))
  pdata['Activation'] = f(pdata$A, pdata$B, rteqn)
  plotd$Activation = 1
  
  p2 = ggplot(pdata, aes(A, B, fill = Activation)) +
    geom_raster() +
    scale_fill_distiller(palette = 'YlOrRd', direction = 1) +
    ggtitle('1 act 1 inhib dependent') +
    theme_minimal() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = 'none'
    ) +
    geom_point(data = plotd, aes(A, B), colour = 'white', alpha = 0.2, size = 2)
  
  lyt = matrix(c(1,1,1,2,2,1,1,1,2,2,3,3,3,3,3), byrow = T,ncol = 5)
  multiplot(p1, p2, histoplot, layout = lyt)
}

simseed = 360
nsamp = 100
```

Input models setting with A, B and C
```{r, echo=FALSE, message=FALSE, warning=FALSE}
#input panel
inputPanel(
  sliderInput('b1mean', label = 'Mean of mixture 1 of B:',
              min = 0.2, max = 0.8, step = 0.1, value = 0.2),
  sliderInput('b2mean', label = 'Mean of mixture 2 of B:',
              min = 0.2, max = 0.8, step = 0.1, value = 0.6),
  sliderInput('bvar', label = 'Variance of B:',
              min = 0.05, max = 0.3, step = 0.05, value = 0.05),
  sliderInput('amean', label = 'Mean of A:',
              min = 0.2, max = 0.8, step = 0.1, value = 0.8),
  sliderInput('avar', label = 'Variance of A:',
              min = 0.05, max = 0.3, step = 0.05, value = 0.1),
  selectInput('type', label = 'Interaction type:',
              choices = c('A OR B', '!A OR !B', '!A OR B', 'A AND B', '!A AND !B', 'A AND !B'), selected = 'A OR B')
)

g = new('GraphGRN')
for (n in c('B', 'A' ,'C')) {
  g = addNodeRNA(g, n)
}
g = addEdgeReg(g, 'B', 'C', activation = T)
g = addEdgeReg(g, 'A', 'C', activation = T)

sim = new('SimulationGRN', graph = g, seed = simseed)

renderPlot({
  #model modification
  inputModels = list('A' = list('prop' = 1,
                                'mean' = as.numeric(input$amean),
                                'sd' = as.numeric(input$avar)),
                     'B' = list('prop' = rep(0.5, 2),
                                'mean' = as.numeric(c(input$b1mean, input$b2mean)),
                                'sd' = as.numeric(rep(input$bvar, 2)))
                     )
  sim$inputModels = inputModels
  
  #plot densities of inputs
  set.seed(simseed)
  # extinputs = matrix(runif(nsamp * 2), ncol = 2)
  # colnames(extinputs) = c('A', 'B')
  extinputs = NULL
  d = simulateDataset(sim, nsamp, extinputs)
  
  plotd = as.data.frame(t(d))
  cors = cor(plotd)
  cors = round(cors, digits = 2)
  
  histd = data.frame('Expr' = c(plotd$A, plotd$B), 'Gene' = rep(c('A', 'B'), each = nrow(plotd)))
  hplot = ggplot(histd, aes(Expr, fill = Gene)) + geom_histogram(alpha = 0.7, position = 'identity') +
    ggtitle(paste('Input data', ' (cor = ', cors['A', 'B'], ')', sep = '')) +
    theme_minimal() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank()
    )
  
  if(input$type %in%  'A OR B'){
  #2 activators OR
  g = new('GraphGRN')
    for (n in LETTERS[1:3]) {
      g = addNodeRNA(g, n)
    }
    g = addEdgeReg(g, 'A', 'C', activation = T)
    g = addEdgeReg(g, 'B', 'C', activation = T)
    getNode(g, 'C')$logiceqn = 'A | B'
    
    sim = new('SimulationGRN', graph = g, seed = simseed)
    sim$inputModels = inputModels
    d = simulateDataset(sim, nsamp)
    plotds(d, 'A OR B', generateRateEqn(getNode(g, 'C'), g), hplot)
  }
  
  if(input$type %in%  '!A OR !B'){
    #2 repressors OR
    g = new('GraphGRN')
    for (n in LETTERS[1:3]) {
      g = addNodeRNA(g, n)
    }
    g = addEdgeReg(g, 'A', 'C', activation = F)
    g = addEdgeReg(g, 'B', 'C', activation = F)
    getNode(g, 'C')$logiceqn = '!A | !B'
    
    sim = new('SimulationGRN', graph = g, seed = simseed)
    sim$inputModels = inputModels
    d = simulateDataset(sim, nsamp)
    plotds(d, '!A OR !B', generateRateEqn(getNode(g, 'C'), g), hplot)
  }
  
  if(input$type %in%  '!A OR B'){
    #1 repressor, 1 Activator OR
    g = new('GraphGRN')
    for (n in LETTERS[1:3]) {
      g = addNodeRNA(g, n)
    }
    g = addEdgeReg(g, 'A', 'C', activation = F)
    g = addEdgeReg(g, 'B', 'C', activation = T)
    getNode(g, 'C')$logiceqn = '!A | B'
    
    sim = new('SimulationGRN', graph = g, seed = simseed)
    sim$inputModels = inputModels
    d = simulateDataset(sim, nsamp)
    plotds(d, '!A OR B', generateRateEqn(getNode(g, 'C'), g), hplot)
  }
  
  if(input$type %in%  'A AND B'){
    #2 activators AND
    g = new('GraphGRN')
    for (n in LETTERS[1:3]) {
      g = addNodeRNA(g, n)
    }
    g = addEdgeReg(g, 'A', 'C', activation = F)
    g = addEdgeReg(g, 'B', 'C', activation = T)
    getNode(g, 'C')$logiceqn = 'A & B'
    
    sim = new('SimulationGRN', graph = g, seed = simseed)
    sim$inputModels = inputModels
    d = simulateDataset(sim, nsamp)
    plotds(d, 'A AND B', generateRateEqn(getNode(g, 'C'), g), hplot)
  }
  
  if(input$type %in%  '!A AND !B'){
    #2 repressors AND
    g = new('GraphGRN')
    for (n in LETTERS[1:3]) {
      g = addNodeRNA(g, n)
    }
    g = addEdgeReg(g, 'A', 'C', activation = F)
    g = addEdgeReg(g, 'B', 'C', activation = T)
    getNode(g, 'C')$logiceqn = '!A & !B'
    
    sim = new('SimulationGRN', graph = g, seed = simseed)
    sim$inputModels = inputModels
    d = simulateDataset(sim, nsamp)
    plotds(d, '!A AND !B', generateRateEqn(getNode(g, 'C'), g), hplot)
  }
  
  if(input$type %in%  'A AND !B'){
    #1 repressor, 1 Activator AND
    g = new('GraphGRN')
    for (n in LETTERS[1:3]) {
      g = addNodeRNA(g, n)
    }
    g = addEdgeReg(g, 'A', 'C', activation = F)
    g = addEdgeReg(g, 'B', 'C', activation = T)
    getNode(g, 'C')$logiceqn = 'A & !B'
    
    sim = new('SimulationGRN', graph = g, seed = simseed)
    sim$inputModels = inputModels
    d = simulateDataset(sim, nsamp)
    plotds(d, 'A AND !B', generateRateEqn(getNode(g, 'C'), g), hplot)
  }
})
```

